import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import assert from 'node:assert/strict';
import {execFileSync} from 'node:child_process';
import {chromium} from '@playwright/test';
const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'ommi-browser-'));
process.env.NODE_ENV='test';process.env.DATABASE_PATH=path.join(tmp,'test.db');process.env.UPLOAD_PATH=path.join(tmp,'uploads');
const {createApplication}=await import('../app.js');const {default:bcrypt}=await import('bcryptjs');
const application=createApplication();application.db.prepare('INSERT INTO users(username,password_hash,role) VALUES (?,?,\'admin\')').run('browser-admin',bcrypt.hashSync('Browser-test-password!',12));
await new Promise(r=>application.server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${application.server.address().port}`;
let browser,tv;const errors=[];fs.mkdirSync('docs/screenshots',{recursive:true});
const checkPage=page=>{page.on('pageerror',e=>{errors.push(e.message);console.log('Browser error:',e.message);});page.on('console',msg=>{if(msg.type()==='error')errors.push(msg.text());});};
try{
 for(const [name,length,color] of [['Video B',97,'0x149b9b'],['Video D',20,'0xe93889']])execFileSync('ffmpeg',['-v','error','-f','lavfi','-i',`color=c=${color}:s=320x180:r=8`,'-t',String(length),'-c:v','libx264','-pix_fmt','yuv420p','-y',path.join(tmp,`${name}.mp4`)],{timeout:60000});
 fs.copyFileSync('IMG_LOGO.png',path.join(tmp,'Image A.png'));fs.copyFileSync('img/17-906.png',path.join(tmp,'Image C.png'));
 browser=await chromium.launch({headless:true,args:['--no-sandbox']});const context=await browser.newContext({viewport:{width:1440,height:1000}});const admin=await context.newPage();checkPage(admin);
 await admin.goto(base+'/admin/login');await admin.screenshot({path:'docs/screenshots/login.png'});await admin.getByLabel('Identifiant',{exact:true}).fill('browser-admin');await admin.getByLabel('Mot de passe',{exact:true}).fill('Browser-test-password!');await admin.getByRole('button',{name:'Se connecter',exact:true}).click();await admin.waitForURL(base+'/admin');await admin.locator('.stat-card').first().waitFor();
 const auth=await (await context.request.get(base+'/auth/session')).json();const headers={'X-CSRF-Token':auth.data.csrfToken};
 const api=async(url,method='GET',data)=>{const r=await context.request.fetch(base+url,{method,headers,data});const result=await r.json();assert.equal(result.success,true,JSON.stringify(result));return result.data;};
 await admin.locator('nav').getByRole('link',{name:'Magasins',exact:true}).click();await admin.getByRole('button',{name:'Ajouter un magasin'}).click();const storeModal=admin.getByRole('dialog');await storeModal.getByLabel('Nom',{exact:true}).fill('Tunis');await storeModal.getByLabel('Code du magasin').fill('TUN');await storeModal.getByLabel('Adresse').fill('Tunis, Tunisie');await storeModal.getByLabel('Afficher l’écran de fermeture').uncheck();await storeModal.getByRole('button',{name:'Enregistrer',exact:true}).click();await storeModal.waitFor({state:'hidden'});console.log('PASS browser: login and store creation');
 await admin.locator('nav').getByRole('link',{name:'Médiathèque',exact:true}).click();await admin.locator('#files').setInputFiles(['Image A.png','Video B.mp4','Image C.png','Video D.mp4'].map(n=>path.join(tmp,n)));await admin.locator('.media-card').nth(3).waitFor({timeout:60000});await admin.screenshot({path:'docs/screenshots/media.png'});console.log('PASS browser: multiple-file upload and thumbnails');
 await admin.locator('nav').getByRole('link',{name:'Playlists',exact:true}).click();await admin.getByRole('button',{name:'Créer une playlist'}).click();const editor=admin.getByRole('dialog');await editor.getByLabel('Nom',{exact:true}).fill('Promotions générales');await editor.getByRole('button',{name:'Ajouter un média'}).click();for(const name of ['Image A.png','Video B.mp4','Image C.png','Video D.mp4'])await editor.locator('.picker-card').filter({hasText:name}).click();await editor.locator('[data-prop="image_duration_seconds"]').nth(0).fill('5');await editor.locator('[data-prop="image_duration_seconds"]').nth(1).fill('8');await admin.screenshot({path:'docs/screenshots/playlist-editor.png'});
 // Move the first image down and back with accessible controls, then use HTML DnD.
 await editor.locator('.playlist-item').first().getByRole('button',{name:'Déplacer vers le bas'}).click();await editor.locator('.playlist-item').nth(1).getByRole('button',{name:'Déplacer vers le haut'}).click();
 await editor.locator('.playlist-item').first().dragTo(editor.locator('.playlist-item').nth(1));await editor.locator('.playlist-item').nth(1).dragTo(editor.locator('.playlist-item').first());
 await editor.getByRole('button',{name:'Enregistrer',exact:true}).click();await editor.waitFor({state:'hidden'});const playlists=await api('/api/playlists');const playlist=await api(`/api/playlists/${playlists[0].id}`);assert.deepEqual(playlist.items.map(i=>i.title),['Image A.png','Video B.mp4','Image C.png','Video D.mp4']);assert.deepEqual(playlist.items.filter(i=>i.type==='image').map(i=>i.image_duration_seconds),[5,8]);
 await admin.locator('nav').getByRole('link',{name:'Groupes d’écrans',exact:true}).click();await admin.getByRole('button',{name:'Créer un groupe'}).click();const groupModal=admin.getByRole('dialog');await groupModal.getByLabel('Nom',{exact:true}).fill('Promotions');await groupModal.locator('select[name="playlist_id"]').selectOption(String(playlist.id));await groupModal.getByRole('button',{name:'Enregistrer',exact:true}).click();await groupModal.waitFor({state:'hidden'});console.log('PASS browser: playlist creation, image durations, drag ordering and group assignment');
 const stores=await api('/api/stores'),groups=await api('/api/groups');const tvContext=await browser.newContext({viewport:{width:1920,height:1080}});tv=await tvContext.newPage();checkPage(tv);
 await tv.addInitScript(()=>{window.playbackEvents=[];const record=slot=>{if(slot.dataset.observed)return;slot.dataset.observed='1';const media=slot.querySelector('img,video');window.playbackEvents.push({type:media.tagName,title:media.alt||media.src,time:performance.now()});};document.addEventListener('ended',e=>{if(e.target.tagName==='VIDEO')window.playbackEvents.push({type:'ENDED',title:e.target.src,time:performance.now(),duration:e.target.duration,currentTime:e.target.currentTime});},true);new MutationObserver(()=>document.querySelectorAll('.media-slot.visible').forEach(record)).observe(document,{childList:true,subtree:true,attributes:true,attributeFilter:['class']});});
 await tv.goto(base+'/display/setup');await tv.locator('#store').selectOption(String(stores[0].id));await tv.locator('#group').selectOption(String(groups[0].id));await tv.screenshot({path:'docs/screenshots/tv-setup.png'});await tv.locator('#start-display').click();await tv.locator('.media-slot.visible img').waitFor();console.log('PASS browser: TV enrollment; beginning real 130-second playback');
 const progress=setInterval(async()=>{try{console.log('Playback progress',await tv.evaluate(()=>({events:window.playbackEvents,video:[...document.querySelectorAll('video')].map(v=>({time:v.currentTime,duration:v.duration,paused:v.paused,ended:v.ended,ready:v.readyState})),brand:document.querySelector('#brand-screen').hidden})));}catch{}},30000);progress.unref();
 await tv.waitForFunction(()=>window.playbackEvents.filter(e=>e.type==='ENDED').length>=2,{},{timeout:150000});await tv.waitForFunction(()=>window.playbackEvents.filter(e=>e.type==='IMG').length>=3,{},{timeout:10000});const events=await tv.evaluate(()=>window.playbackEvents);const visible=events.filter(e=>e.type!=='ENDED');assert.deepEqual(visible.slice(0,5).map(x=>x.type),['IMG','VIDEO','IMG','VIDEO','IMG']);const timings=visible.slice(1,5).map((e,i)=>(e.time-visible[i].time)/1000);for(const [i,expected]of [5,97,8,20].entries())assert.ok(Math.abs(timings[i]-expected)<2,`${expected}s expected, got ${timings[i]}s`);for(const e of events.filter(x=>x.type==='ENDED'))assert.ok(Math.abs(e.currentTime-e.duration)<.1);clearInterval(progress);console.log('PASS browser: real media timings',timings.map(x=>x.toFixed(2)), 'videos completed');
 await admin.goto(base+'/admin');await admin.locator('.stat-card').first().waitFor();await admin.screenshot({path:'docs/screenshots/dashboard.png'});
 // Live update during the next 97-second video must remain pending.
 await tv.waitForFunction(()=>window.playbackEvents.filter(e=>e.type==='VIDEO').length>=3,{},{timeout:10000});await api(`/api/playlists/${playlist.id}`,'PUT',{name:playlist.name,items:[{media_id:playlist.items[2].media_id,image_duration_seconds:8}]});await tv.waitForTimeout(1200);assert.equal(await tv.locator('.media-slot.visible video').count(),1);assert.ok(await tv.locator('.media-slot.visible video').evaluate(v=>v.currentTime>0&&!v.paused));
 // Advance near the end by seeking; ended must commit the pending playlist.
 await tv.locator('.media-slot.visible video').evaluate(v=>{v.currentTime=v.duration-.3;});await tv.locator('.media-slot.visible img[alt="Image C.png"]').waitFor({timeout:10000});console.log('PASS browser: Socket.IO update deferred until video ended');
 const closed={...stores[0],closed_screen_enabled:1,hours:stores[0].hours.map(h=>({...h,is_closed:1}))};await api(`/api/stores/${stores[0].id}`,'PUT',closed);await tv.getByText('Nous sommes actuellement fermés.',{exact:true}).waitFor({timeout:10000});await tv.screenshot({path:'docs/screenshots/closed-screen.png'});await api(`/api/stores/${stores[0].id}`,'PUT',{...closed,closed_screen_enabled:0});await tv.locator('.media-slot.visible img').waitFor({timeout:10000});console.log('PASS browser: live opening-hours change and automatic resume');
 await tv.keyboard.press('Control+Shift+KeyD');await tv.locator('#diagnostics').waitFor({state:'visible'});assert.equal((await api('/api/displays'))[0].online,1);await tv.reload();await tv.locator('.media-slot.visible img').waitFor({timeout:10000});assert.equal(await tv.locator('#setup').isVisible(),false);console.log('PASS browser: heartbeat, diagnostics, remembered setup');
 for(const route of ['stores','groups','displays','media','playlists','scheduling','users','settings']){await admin.goto(base+'/admin/'+route);await admin.locator('.page-heading').waitFor();assert.equal(await admin.locator('#content .skeleton').count(),0);}
 await admin.setViewportSize({width:390,height:844});await admin.goto(base+'/admin/media');await admin.locator('.media-card').first().waitFor();assert.ok(await admin.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await admin.locator('#menu-toggle').click();assert.equal(await admin.locator('#sidebar').evaluate(e=>e.classList.contains('open')),true);await admin.screenshot({path:'docs/screenshots/mobile.png'});console.log('PASS browser: all admin routes, mobile navigation and no horizontal overflow');
 assert.deepEqual(errors,[]);console.log('PASS browser: no JavaScript or console errors');
}catch(e){if(tv){console.log('Playback failure state',await tv.evaluate(()=>({events:window.playbackEvents,html:document.querySelector('#player').innerHTML.slice(0,4000)})).catch(()=>null));await tv.screenshot({path:'/tmp/ommi-player-failure.png'}).catch(()=>{});}console.log('Console errors',errors);throw e;}finally{await browser?.close();await application.close();fs.rmSync(tmp,{recursive:true,force:true});}
